name: 'Get PR from GitHub'
description: 'Get PR from GitHub'
inputs:
  GITHUB_TOKEN :
    description: 'GitHub Token for getting the pull request'
    required: true
  PullRequestNumber :
    description: 'Pull request number'
    required: true
outputs:
  pullRequestState:
    description: 'State of found pull request'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'green'