name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get pull request number
        uses: bnlinhlang/GitHubActionPractice@1.0.0
        id: get_pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullrequestnumber: 5
      - name: show result
        run: echo pull request state ${{ steps.get_pr.outputs.status }}
